# outage_detection 
## problem statement - we have to help the company predict outage duration .

# Importing our necessary libraries 

In [1]:
import pandas as pd
import numpy as np
import os



# Visualization libraries.


In [2]:
os.chdir("C:/Users/LENOVO PC/Desktop/aman/phd/data/imp")

# Lets begin with Exploratory Data Analysis

In [3]:
df1 = pd.read_csv('broadband_data.csv')

In [4]:
df2 = pd.read_csv('report_data.csv')

In [5]:
df3 = pd.read_csv('server_data.csv')

In [6]:
df4 = pd.read_csv('outage_data.csv')

In [7]:
df5 = pd.read_csv('train_data.csv')

## Merging the Dataframes 

In [8]:
df6 =pd.merge(df2,df1,on = "id", how ='left')

In [9]:
df7 = pd.merge(df3,df4,on="id",how = 'left')

In [10]:
df8 = pd.merge(df6,df7,on ="id", how = 'left')

In [11]:
data = pd.merge(df8,df5,on = "id")
data.shape

(48973, 8)

In [12]:
data.dtypes

id                      int64
log_report_type        object
volume                  int64
broadband_type         object
transit_server_type    object
outage_type            object
area_code              object
outage_duration         int64
dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['log_report_type']= label_encoder.fit_transform(data['log_report_type']) 
print(data.head())


     id  log_report_type  volume    broadband_type     transit_server_type  \
0  8011              283       7  broadband_type_8  transit_server_type_15   
1  2588              298       9  broadband_type_8  transit_server_type_15   
2  2588              298       9  broadband_type_8  transit_server_type_11   
3  2588               98       5  broadband_type_8  transit_server_type_15   
4  2588               98       5  broadband_type_8  transit_server_type_11   

     outage_type area_code  outage_duration  
0  outage_type_2    area_1                0  
1  outage_type_1    area_1                0  
2  outage_type_1    area_1                0  
3  outage_type_1    area_1                0  
4  outage_type_1    area_1                0  


In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['area_code']= label_encoder.fit_transform(data['area_code']) 
print(data.head())


     id  log_report_type  volume    broadband_type     transit_server_type  \
0  8011              283       7  broadband_type_8  transit_server_type_15   
1  2588              298       9  broadband_type_8  transit_server_type_15   
2  2588              298       9  broadband_type_8  transit_server_type_11   
3  2588               98       5  broadband_type_8  transit_server_type_15   
4  2588               98       5  broadband_type_8  transit_server_type_11   

     outage_type  area_code  outage_duration  
0  outage_type_2          0                0  
1  outage_type_1          0                0  
2  outage_type_1          0                0  
3  outage_type_1          0                0  
4  outage_type_1          0                0  


In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['outage_type']= label_encoder.fit_transform(data['outage_type']) 
print(data.head())


     id  log_report_type  volume    broadband_type     transit_server_type  \
0  8011              283       7  broadband_type_8  transit_server_type_15   
1  2588              298       9  broadband_type_8  transit_server_type_15   
2  2588              298       9  broadband_type_8  transit_server_type_11   
3  2588               98       5  broadband_type_8  transit_server_type_15   
4  2588               98       5  broadband_type_8  transit_server_type_11   

   outage_type  area_code  outage_duration  
0            1          0                0  
1            0          0                0  
2            0          0                0  
3            0          0                0  
4            0          0                0  


In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['broadband_type']= label_encoder.fit_transform(data['broadband_type']) 
print(data.head())

     id  log_report_type  volume  broadband_type     transit_server_type  \
0  8011              283       7               8  transit_server_type_15   
1  2588              298       9               8  transit_server_type_15   
2  2588              298       9               8  transit_server_type_11   
3  2588               98       5               8  transit_server_type_15   
4  2588               98       5               8  transit_server_type_11   

   outage_type  area_code  outage_duration  
0            1          0                0  
1            0          0                0  
2            0          0                0  
3            0          0                0  
4            0          0                0  


In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
data['transit_server_type']= label_encoder.fit_transform(data['transit_server_type']) 
print(data.head())

     id  log_report_type  volume  broadband_type  transit_server_type  \
0  8011              283       7               8                    6   
1  2588              298       9               8                    6   
2  2588              298       9               8                    2   
3  2588               98       5               8                    6   
4  2588               98       5               8                    2   

   outage_type  area_code  outage_duration  
0            1          0                0  
1            0          0                0  
2            0          0                0  
3            0          0                0  
4            0          0                0  


## droping "id" column 

In [18]:

data.drop(columns = ["id"], axis = 1, inplace = True)

In [19]:
data.shape

(48973, 7)

# Separating our dependant and independant variables.

In [20]:
X = data.drop('outage_duration', axis = 1)
y = data['outage_duration']

# Train Test Split

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 123)

In [22]:
X_train.shape

(34281, 6)

In [23]:
X_test.shape

(14692, 6)

In [24]:
y_train.shape

(34281,)

In [25]:
y_test.shape

(14692,)

# Model building and evaluation

In [26]:
from sklearn.model_selection import GridSearchCV

def model_building(X, y, test, model, params = None, k = 1) :
    
    if params == None :
        model.fit(X, y)
        
        # return fitted model & train-test predictions
        return (model, model.predict(X), model.predict(test))
    
    else :
        model_cv = GridSearchCV(model, param_grid = params, cv = k)
        model_cv.fit(X, y)
        model = model_cv
        
        
        # return and extra object for all cross validation operations
        return (model_cv, model, model.predict(X), model.predict(test))

In [27]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score

def model_evaluation(y_train, pred_train, y_test, pred_test) :
    
    print('''
            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================''')
    print(classification_report(y_train, pred_train))
    print("f1_score: ",f1_score(y_train,pred_train, average= "macro")) 
    print('\nConfusion Matrix :')
    print(confusion_matrix(y_test, pred_test) ) 
    print('\nAccuracy Score :', accuracy_score(y_test, pred_test)) 
    
    
    print('''
            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================''')
    print(classification_report(y_test, pred_test))
    print("f1_score: ",f1_score(y_test,pred_test, average = "macro" ))
    print('\nConfusion Matrix :')
    print(confusion_matrix(y_test, pred_test) ) 
    print('\nAccuracy Score :', accuracy_score(y_test, pred_test)) 

## logistic regression

In [28]:
from sklearn.linear_model import LogisticRegression

model, pred_train, pred_test = model_building(X_train, y_train, X_test, LogisticRegression())

In [29]:
model_evaluation(y_train, pred_train, y_test, pred_test)


               CLASSIFICATION REPORT FOR TRAIN DATA
             precision    recall  f1-score   support

          0       0.63      0.88      0.74     20538
          1       0.40      0.25      0.30      8987
          2       0.43      0.01      0.02      4756

avg / total       0.54      0.60      0.52     34281

f1_score:  0.3530593608130444

Confusion Matrix :
[[7725 1069   15]
 [2858  964    3]
 [1617  431   10]]

Accuracy Score : 0.5920909338415464

               CLASSIFICATION REPORT FOR TEST DATA
             precision    recall  f1-score   support

          0       0.63      0.88      0.74      8809
          1       0.39      0.25      0.31      3825
          2       0.36      0.00      0.01      2058

avg / total       0.53      0.59      0.52     14692

f1_score:  0.350517954719248

Confusion Matrix :
[[7725 1069   15]
 [2858  964    3]
 [1617  431   10]]

Accuracy Score : 0.5920909338415464


## Bagging classifier

In [30]:
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier

estimators = [BaggingClassifier(random_state=123),
              AdaBoostClassifier(random_state=123), 
              RandomForestClassifier(random_state=123), 
              GradientBoostingClassifier(random_state=123)]

for estimator in estimators :

    model, pred_train, pred_test = model_building(X_train, y_train,
                                                  X_test, estimator)
    
    print('===================================================================\n\t\t\t',
          type(estimator).__name__,
          '\n===================================================================\n')
    
    model_evaluation(y_train, pred_train, y_test, pred_test)

C:\Users\LENOVO PC\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


			 BaggingClassifier 


               CLASSIFICATION REPORT FOR TRAIN DATA
             precision    recall  f1-score   support

          0       0.96      0.97      0.96     20538
          1       0.91      0.91      0.91      8987
          2       0.94      0.91      0.92      4756

avg / total       0.94      0.94      0.94     34281

f1_score:  0.9329294005444512

Confusion Matrix :
[[7808  796  205]
 [ 855 2763  207]
 [ 304  260 1494]]

Accuracy Score : 0.8211952082766131

               CLASSIFICATION REPORT FOR TEST DATA
             precision    recall  f1-score   support

          0       0.87      0.89      0.88      8809
          1       0.72      0.72      0.72      3825
          2       0.78      0.73      0.75      2058

avg / total       0.82      0.82      0.82     14692

f1_score:  0.7850639474997023

Confusion Matrix :
[[7808  796  205]
 [ 855 2763  207]
 [ 304  260 1494]]

Accuracy Score : 0.8211952082766131
			 AdaBoostClassifier 


               CLASSIFICA

In [31]:
df = pd.read_csv('test_data.csv')

In [32]:
df.dtypes

id            int64
area_code    object
dtype: object

In [ ]:
test1 = test_data['id']

In [33]:
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder() 
df['area_code']= label_encoder.fit_transform(df['area_code']) 
print(df.head())

      id  area_code
0   3340        190
1  14067        494
2   1134        105
3     27        405
4   9793        190


In [34]:
test_data = pd.merge(data,df,on = 'area_code' , how = "right")
test_data.shape

(74664, 8)

In [35]:
test_data.head(10)

log_report_type  volume  broadband_type  transit_server_type  outage_type  \
0              283       7               8                    6            1   
1              298       9               8                    6            0   
2              298       9               8                    2            0   
3               98       5               8                    6            0   
4               98       5               8                    2            0   
5              296      15               8                    6            0   
6              296      15               8                    2            0   
7              100       5               8                    6            0   
8              100       5               8                    2            0   
9              272       3               8                    2            0   

   area_code  outage_duration    id  
0          0                0  8148  
1          0                0  8148  
2          0                0  8148  
3          0                0  8148  
4          0                0  8148  
5          0                0  8148  
6          0                0  8148  
7          0                0  8148  
8          0                0  8148  
9          0                0  8148

In [55]:
test1 = df['id']

In [56]:
test1.shape

(1477,)

In [40]:
test_data.dtypes

log_report_type        int64
volume                 int64
broadband_type         int64
transit_server_type    int64
outage_type            int64
area_code              int64
outage_duration        int64
id                     int64
dtype: object

In [41]:
test_datadp = test_data[test_data.duplicated()]
test_datadp

log_report_type  volume  broadband_type  transit_server_type  \
31                  69       2               8                    2   
32                  69       2               8                    6   
51                  98       2               8                    6   
52                  98       2               8                    2   
64                 298       2               8                    6   
65                 298       2               8                    2   
70                 272       1               8                    6   
71                 272       1               8                    2   
124                272       1               8                    2   
125                272       1               8                    6   
128                296       2               8                    2   
129                296       2               8                    6   
142                296       1               8                    6   
143                296       1               8                    2   
147                296       1               8                    6   
180                 69       2               8                    2   
181                 69       2               8                    6   
200                 98       2               8                    6   
201                 98       2               8                    2   
213                298       2               8                    6   
214                298       2               8                    2   
219                272       1               8                    6   
220                272       1               8                    2   
273                272       1               8                    2   
274                272       1               8                    6   
277                296       2               8                    2   
278                296       2               8                    6   
291                296       1               8                    6   
292                296       1               8                    2   
296                296       1               8                    6   
...                ...     ...             ...                  ...   
73752              267       1               2                    2   
73754              267       1               2                   44   
73761               63       1               8                    2   
73763               63       1               8                   44   
73764               63       1               2                    2   
73766               63       1               2                   44   
74102               31       1               2                   11   
74103              117       1               2                   11   
74132              116       1               2                   10   
74150               30       1               2                   10   
74167              116       1               2                   10   
74185               30       1               2                   10   
74202              116       1               2                   10   
74220               30       1               2                   10   
74495               90       3               8                    2   
74511               90       3               8                    2   
74527               90       3               8                    2   
74543               90       3               8                    2   
74559               90       3               8                    2   
74575               90       3               8                    2   
74624              288       6               8                    2   
74626              288       1               8                    2   
74630               90       7               8                    2   
74631              288       2               8                    2   
74632               90       2 

In [42]:
test_data.drop_duplicates(subset = "id", inplace = True)

In [48]:
test_data.shape

(1477, 6)

In [46]:
test_data.dtypes

log_report_type        int64
volume                 int64
broadband_type         int64
transit_server_type    int64
outage_type            int64
area_code              int64
outage_duration        int64
dtype: object

In [44]:
test_data.drop(["id"],axis = 1 , inplace= True)

In [47]:
test_data.drop(["outage_duration"],axis = 1 , inplace= True)

## DecisionTree Classifier 

In [49]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [50]:
output = classifier.predict(test_data)
output

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [52]:
output.shape

(1477,)

In [57]:
  output = pd.DataFrame({
        "id": test1,
        "outage_duration": output
    })

output.to_csv('submi.csv', index=False)

In [58]:
output

id  outage_duration
0      3340                0
1     14067                0
2      1134                0
3        27                0
4      9793                0
5     12010                0
6      7213                0
7     16347                0
8      8811                0
9     17705                0
10     7886                1
11     2722                1
12    17659                2
13     7518                2
14     7423                2
15     6174                2
16     8504                2
17    15199                2
18     4403                2
19     3778                2
20    13341                2
21     3271                2
22    11125                2
23    11786                2
24     8572                2
25    14129                2
26    18375                0
27     3711                0
28     4750                0
29     9510                0
...     ...              ...
1447    583                2
1448  14505                0
1449  18193                1
1450  11992                0
1451  10455                0
1452   9132                0
1453  14611                0
1454   4552                0
1455   8564                0
1456   2857                0
1457   3122                0
1458  15017                0
1459  14009                0
1460   1378                0
1461  10752                0
1462   6551                0
1463  11311                0
1464   8099                0
1465   5464                0
1466  14735                1
1467   7221                1
1468  13377                1
1469  15505                1
1470   1967                1
1471   8582                1
1472   7975                1
1473  10664                1
1474   7753                1
1475    989                1
1476   3129                1

[1477 rows x 2 columns]

In [59]:
output['outage_duration'].nunique()

3

In [60]:
output[['id','outage_duration']].to_csv(r'C:\Users\LENOVO PC\Desktop\aman\submi.csv',index=False)